#include "Adherent.h"




void Adherent::emprunterLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008A0 begin
{
}
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008A0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adherent::rendreLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008A2 begin
{
}
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008A2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
