#include "Bibliothèque.h"




void Bibliothèque::ajouterAdherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008D2 begin
{
}
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008D2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliothèque::enleverAdherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008D4 begin
{
}
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008D4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliothèque::ajouterDocument()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008D6 begin
{
}
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008D6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
