#include "Livre.h"




void Livre::empruntable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008C2 begin
{
}
// section -87--2--113--45-3b91b15b:16f24cb09c3:-8000:00000000000008C2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
